### ISSUE TITLE
Breaks in Strict Mode

### ISSUE THREAD

**Issue by ghost** [KingPixil/moon-cli#1]
When I type in `moon help`, it gives me this error:

```
const rl = readline.createInterface({
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Just wanted to let you know :smile:

**Comment by kbrsh** [comment]
First of all, `help` isn't a command, adding the option `--help` is. But this will be fixed in the next version. The strict mode issue should be fixed as well.
