### ISSUE TITLE
watch-css crashes, bundle-css works

### ISSUE THREAD

**Issue by NaakkaDev** [KingPixil/moon-cli#15]
`npm run watch-css` is having a bad day and I cannot figure out why since `npm run bundle-css` works without problems.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kbrsh** [comment]
Looks like it isn't able to run `npm run bundle-css` correctly. Can you grab the new `build/watch.js` file from this repo and try again?

**Comment by NaakkaDev** [comment]
~Looks like that doesn't even see the changes to the css file.~ Works fine actually, assumed things because of no output. 👍 

Side note: Took me a while to find the template source, should put a link to that in moon-cli readme.
