### ISSUE TITLE
First time installing moon cli: moon-template.tar.gz not readable

### ISSUE THREAD

**Issue by marcocastignoli** [KingPixil/moon-cli#18]
```bash
/home/marcocastignoli/.npm-global/lib/node_modules/moon-cli/index.js:43
		if (err) throw err;
		         ^

Error: Command failed: mkdir /prj/experiments/init; tar -xzf /home/marcocastignoli/.npm-global/lib/node_modules/moon-cli/moon-template.tar.gz -C /prj/experiments/init --strip=1

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:135:13)
    at ChildProcess.emit (events.js:224:7)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at Pipe._handle.close [as _onclose] (net.js:558:12)
```

When I try to open moon-template.tar.gz, it gives me an error:
```bash
$ tar -xzvf moon-template.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by kbrsh** [comment]
Hmm, maybe the tarball didn't install correctly? Can you check the size/contents of the tar.gz file and check if it actually contains something?

**Comment by marcocastignoli** [comment]
The moon-template.tar.gz is 77 bytes and I cannot check because I can't open it

**Comment by kbrsh** [comment]
Interesting. Can you attempt to diagnose the type of file? Try using `file`.

```sh
file moon-template.tar.gz
```

If it doesn't work, try using `cat` to check if it is in fact a binary file.

**Comment by marcocastignoli** [comment]
```bash
$ file moon-template.tar.gz
moon-template.tar.gz: ASCII text, with no line terminators
```
I think the cat reveal the problem, I didn't think about opening in with a text editor
```bash
$ cat moon-template.tar.gz 
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
```

**Comment by marcocastignoli** [comment]
News?

**Comment by kbrsh** [comment]
Hey! What command did you use to run the CLI? You may have accidentally added a custom template URL as the second argument.

Try running:

```sh
moon app
```

Under the hood, this equates to:

```sh
moon app kbrsh/moon-template
```

This is due to the fact that the `moon-template` repository is used as a template by default.

**Comment by phongever** [comment]
I am using window to init project. I found some problems with the execute script. I think you need to replace `\` to `/` and add `--force-local` option to the script. I changed and it worked
