### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by ghost** [KingPixil/moon-cli#2]
```
kovirolik@castle ~/WebstormProjects/KEEngine $ moon init frontend
/usr/local/lib/node_modules/moon-cli/bin/moon:79
    let filePath = path.join(dir, files[i]);
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**Comment by ghost** [comment]
I just done `git clone https://github.com/KingPixil/moon-template.git frontend` , but issue still exists =(

**Comment by kbrsh** [comment]
`git clone`ing the template won't work, you need to use the CLI. I'm fixing this issue right now though, should be fixed in the next version.

**Comment by kbrsh** [comment]
I've updated the template as well, so it should be fixed 👍

**Comment by ghost** [comment]
Thank you
