### ISSUE TITLE
init: generating template process breaks on "no such file or directory"

### ISSUE THREAD

**Issue by bmcminn** [KingPixil/moon-cli#3]
OS: Win 7 Professional 64bit
Node: 7.2.0
NPM: 3.10.9

-----

    Z:\github
    λ moon init test-moon
    ======= MOON =======
        [?] Author  Brandtley McMinn
        [?] Description  A Moon App
        [?] Moon Version  0.9.0

        ⣻ generating template fs.js:854
      return binding.mkdir(pathModule._makeLong(path),
                     ^

    Error: ENOENT: no such file or directory, mkdir 'Z:\github\test-moon\dist\js'
        at Object.fs.mkdirSync (fs.js:854:18)
        at dir.split.reduce (Q:\nvm\v7.2.0\node_modules\moon-cli\bin\moon:68:12)
        at Array.reduce (native)
        at mkdirp (Q:\nvm\v7.2.0\node_modules\moon-cli\bin\moon:65:6)
        at download (Q:\nvm\v7.2.0\node_modules\moon-cli\bin\moon:171:9)
        at Q:\nvm\v7.2.0\node_modules\moon-cli\node_modules\download-git-repo\index.js:43:22
        at Q:\nvm\v7.2.0\node_modules\moon-cli\node_modules\download\index.js:165:3
        at callback (Q:\nvm\v7.2.0\node_modules\moon-cli\node_modules\each-async\index.js:38:4)
        at onetime (Q:\nvm\v7.2.0\node_modules\moon-cli\node_modules\onetime\index.js:22:12)
        at Q:\nvm\v7.2.0\node_modules\moon-cli\node_modules\download\index.js:156:5

Looks like the CLI utility doesn't initialize the project directory structure correctly before writing contents to disk.

**Comment by kbrsh** [comment]
Odd, try installing v0.10.0 and running again

**Comment by bmcminn** [comment]
Alright, seems to work under `0.10.0` just fine.
