### ISSUE TITLE
moon init breaking

### ISSUE THREAD

**Issue by karkowg** [KingPixil/moon-cli#8]
``` bash
karkowg@kepler:~/web$
uname -a && node --version && npm --version
Linux kepler 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
v6.10.3
3.10.10

karkowg@kepler:~/web$
moon init caroles
======= MOON =======
    [?] Author  Gustavo Karkow
    [?] Description  A Moon App
    [?] Moon Version  0.9.0

    ⣾ generating template fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/moon-cli/template/config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at download (/usr/lib/node_modules/moon-cli/bin/moon:165:36)
    at /usr/lib/node_modules/moon-cli/node_modules/download-git-repo/index.js:43:29
    at /usr/lib/node_modules/moon-cli/node_modules/download/index.js:161:4
    at DuplexWrapper.callback (/usr/lib/node_modules/moon-cli/node_modules/each-async/index.js:33:4)
    at DuplexWrapper.onetime (/usr/lib/node_modules/moon-cli/node_modules/onetime/index.js:22:12)
    at emitOne (events.js:96:13)
    at DuplexWrapper.emit (events.js:188:7)
```

**Comment by kbrsh** [comment]
Hmm, it seems like the template wasn't downloaded correctly. Can you try running it again and seeing what happens? If the same thing happens, can you give me the output of:

```sh
$ cd /usr/lib/node_modules/moon-cli/; ls template
```

**Comment by karkowg** [comment]
The template dir doesn't exist.

**Comment by kbrsh** [comment]
It didn't install the template correctly then 🤔 

Did you try running the `moon init` command again? I've tried on my machine and it works, not sure why it isn't installing correctly on yours.

**Comment by karkowg** [comment]
I did a local installation of moon-cli now and it worked. Maybe it's a permission issue with the global one.

Sorry for the trouble.

**Comment by kbrsh** [comment]
Alright cool! 👍
